name: Deploy Monitoring Stack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Test DNS Resolution
        run: nslookup mcoricky.duckdns.org

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: mcoricky.duckdns.org
          username: ricky
          port: 22
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/ricky/monitoring-stack
            if [ -d ".git" ]; then
            git pull origin main
            else
            git clone https://${{ secrets.GH_TOKEN }}@github.com/MCORicky/monitoring-stack.git .
             fi
             docker-compose pull
            docker-compose up -d
